# Generated by Django 3.1.2 on 2020-11-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=120)),
                ('trainer_username', models.CharField(max_length=120, unique=True)),
                ('trainer_mail', models.CharField(max_length=120, unique=True)),
                ('trainer_pass', models.CharField(max_length=120)),
                ('trainer_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institution.skillmodel')),
            ],
        ),
    ]
