# Generated by Django 3.1.2 on 2020-11-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainerModel',
        ),
    ]
