# Generated by Django 3.1.2 on 2020-11-19 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institution', '0002_jobmodel'),
        ('Trainers', '0002_delete_trainermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institution.skillmodel')),
            ],
        ),
    ]
