# Generated by Django 3.1.2 on 2020-11-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institution', '0002_jobmodel'),
        ('Trainers', '0003_skillfiltermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillfiltermodel',
            name='Skill',
            field=models.ForeignKey(default='select', on_delete=django.db.models.deletion.CASCADE, to='Institution.skillmodel'),
        ),
    ]
