# Generated by Django 3.1.2 on 2020-11-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainers', '0006_jobapplymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplymodel',
            old_name='firstname',
            new_name='first_name',
        ),
    ]
