# Generated by Django 3.1.2 on 2020-11-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainers', '0007_auto_20201119_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplymodel',
            name='status',
            field=models.CharField(default='applied', max_length=100),
        ),
    ]
