# Generated by Django 3.1.2 on 2020-11-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainers', '0008_jobapplymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplymodel',
            name='phone',
            field=models.IntegerField(default=7356610748),
        ),
    ]
