# Generated by Django 3.1.2 on 2020-11-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainers', '0009_jobapplymodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplymodel',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
