# Generated by Django 3.1.2 on 2020-11-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainers', '0010_auto_20201121_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplymodel',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='applied', max_length=100),
        ),
    ]
